AllCops:
  TargetRubyVersion: 2.3
  # Include common Ruby source files.
  Include:
    - '**/*.gemspec'
    - '**/*.jb'
    - '**/*.jbuilder'
    - '**/*.rake'
    - '**/*.ru'
    - '**/*.ruby'
    - '**/*.spec'
    - '**/*.thor'
    - '**/*.watchr'
    - '**/.irbrc'
    - '**/.pryrc'
    - '**/config.ru'
    - '**/Capfile'
    - '**/Gemfile'
    - '**/Guardfile'
    - '**/Rakefile'
  Exclude:
    - 'vendor/**/*'
# From: https://raw.githubusercontent.com/bbatsov/rubocop/master/config/enabled.yml
Style/SingleLineMethods:
  Enabled: false
Style/EndOfLine:
  EnforcedStyle: lf
Layout/EndOfLine:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: false
