# https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
version: '2'
services:
  rethinkdb:
    container_name: rethinkdb
    image: greyarch/rethinkdb
    ports:
      - "28015:28015"
      - "8080:8080"
#    volumes:
#      - /docker_volumes/buyma_insider/rethinkdb/data:/data
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:latest
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - /docker_volumes/buyma_insider/elasticsearch/config:/usr/share/elasticsearch/config
    ports:
      - "9200:9200"
