version: '2'
services:
  rethinkdb:
    container_name: rethinkdb
    image: greyarch/rethinkdb
    ports:
      - "28015:28015"
      - "8080:8080"
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
  elasticsearch:
    container_name: elastic
    image: elasticsearch:latest
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
