# https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
version: '2'
services:
  rethinkdb:
    container_name: rethinkdb
    image: greyarch/rethinkdb
    ports:
      - "28015:28015"
      - "8080:8080"
#    networks:
#      - buymainsider_default
#    volumes:
#      - /docker_volumes/buyma_insider/rethinkdb/data:/data
  postgres:
    container_name: postgres
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=mobara"
#    networks:
#      - buymainsider_default
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
#    networks:
#      - buymainsider_default
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:latest
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - /docker_volumes/buyma_insider/elasticsearch/config:/usr/share/elasticsearch/config
    ports:
      - "9200:9200"
#    networks:
#      - buymainsider_default
  sidekiq:
    container_name: buyma_insider_sidekiq
    image: buyma_insider_sidekiq:latest
#    networks:
#      - buymainsider_default
#networks:
#  buymainsider_default:
#    driver: bridge
