dynamic:                     strict
properties:
  merchant_id:
    type:                    keyword
  sku:
    type:                    keyword
  name:
    type:                    text
    analyzer:                article_name_analyzer
    fields:
      strict_keyword:
        type:                 text
        analyzer: article_name_strict_keyword_analyzer
      raw:
        # Does this needs to be boosted?
        type:                keyword
        ignore_above:        500
  price:
    type:                    scaled_float
    scaling_factor:          100
  price_history:
    type:                    nested
    properties:
      currency:
        type:                keyword
      history:
        type:                nested
        properties:
          price:
            type:            scaled_float
            scaling_factor:  100
          timestamp:
            type:            date
      created_at:
        type:                date
      updated_at:
        type:                date
  description:
    type:                    text
    analyzer:                article_description_analyzer
  link:
    type:                    text
    analyzer:                article_link_analyzer
  created_at:
    type:                    date
  updated_at:
    type:                    date
