dynamic:                 strict
properties:
  article_id:
    type:                keyword
  currency:
    type:                keyword
  history:
    type:                nested
    properties:
      price:
        type:            scaled_float
        scaling_factor:  100
      timestamp:
        type:            date
  created_at:
    type:                date
  updated_at:
    type:                date
