article_analyzer:
  type: custom
  char_filter:
    - article_char_filter
  tokenizer: standard
  filter:
    - standard
    - lowercase                    
    - asciifolding                # Fold to ascii
    - apostrophe                  # Remove apostrophe
    - stop                        # Remove common english stop words
    - colors_stop_filter          # Remove colors
    - garment_types_stop_filter   # Remove types
    - garment_sizes_stop_filter   # Remove sizes
    - snowball                    # Simplify terms to base, remove plurials