# Require explicit index creation
action.auto_create_index: false

# Require manual setup document mapping
index.mapper.dynamic: false

# Closed indices has no overhead except metadata
# and is blocked for r/w
cluster.indices.close.enable: false
