garment_types_stop_filter: # Based on elasticsearch/wordlists/garment_types.txt
  type: stop
  stopwords:
    - abaya
    - anorak
    - apparel
    - apron
    - ascot tie
    - attire
    - baby grow
    - bag
    - balaclava
    - ball gown
    - bandanna
    - baseball cap
    - bathing suit
    - battledress
    - beanie
    - bedclothes
    - bell-bottoms
    - belt
    - beret
    - bermuda shorts
    - bib
    - bikini
    - blazer
    - bloomers
    - blouse
    - boa
    - bonnet
    - boot
    - boots
    - bow
    - bow tie
    - boxer shorts
    - boxers
    - bra
    - bra knicker set
    - bracelet
    - brassiere
    - breeches
    - briefs
    - buckle
    - button
    - button-down shirt
    - caftan
    - camisole
    - camouflage
    - cap
    - cap and gown
    - cape
    - capris
    - cardigan
    - cargos
    - catsuit
    - chemise
    - cloak
    - clogs
    - clothes
    - clothing
    - coat
    - collar
    - corset
    - costume
    - coveralls
    - cowboy boots
    - cowboy hat
    - cravat
    - crown
    - cuff
    - cuff links
    - cufflinks
    - culottes
    - cummerbund
    - dashiki
    - diaper
    - dinner jacket
    - dirndl
    - drawers
    - dress
    - dress shirt
    - dressing gown
    - duds
    - dungarees
    - earmuffs
    - earrings
    - elastic
    - evening gown
    - fashion
    - fatigues
    - fedora
    - fez
    - flak jacket
    - flannel nightgown
    - flannel shirt
    - fleece
    - flip-flops
    - formal wear
    - frock
    - fur
    - fur coat
    - gabardine
    - gaiters
    - galoshes
    - garb
    - garment
    - garters
    - gear
    - getup
    - gilet
    - girdle
    - glasses
    - gloves
    - gown
    - hair accessory
    - halter top
    - handbag
    - handkerchief
    - hat
    - hawaiian shirt
    - hazmat suit
    - headscarf
    - helmet
    - hem
    - high heels
    - hoodie
    - hoody
    - hook and eye
    - hose
    - hosiery
    - hospital gown
    - houndstooth
    - housecoat
    - jacket
    - jeans
    - jersey
    - jewellery
    - jewelry
    - jodhpurs
    - jogging suit
    - jumper
    - jumpsuit
    - kaftan
    - kerchief
    - khakis
    - kilt
    - kimono
    - kit
    - knickers
    - kurta
    - lab coat
    - lapel
    - leather jacket
    - leg warmers
    - leggings
    - leotard
    - life jacket
    - lingerie
    - loafers
    - loincloth
    - long underwear
    - longjohns
    - miniskirt
    - mittens
    - moccasins
    - muffler
    - mumu
    - neckerchief
    - necklace
    - nightgown
    - nightshirt
    - nightwear
    - onesies
    - outerwear
    - outfit
    - overalls
    - overcoat
    - overshirt
    - pajamas
    - panama hat
    - pants
    - pantsuit
    - pantyhose
    - parka
    - pashmina
    - pea coat
    - peplum
    - petticoat
    - pinafore
    - pleat
    - pocket
    - pocketbook
    - polo shirt
    - poncho
    - poodle skirt
    - porkpie hat
    - pullover
    - pumps
    - purse
    - pyjamas
    - raincoat
    - ring
    - robe
    - romper
    - rugby shirt
    - sandals
    - sari
    - sarong
    - scarf
    - school uniform
    - scrubs
    - shawl
    - sheath dress
    - shellsuit
    - shift
    - shirt
    - shoe
    - shoes
    - shorts
    - shoulder pads
    - shrug
    - singlet
    - skirt
    - slacks
    - slip
    - slippers
    - smock
    - snaps
    - sneakers
    - sock
    - socks
    - sombrero
    - spacesuit
    - stetson hat
    - stockings
    - stole
    - suit
    - sun hat
    - sunbonnet
    - sundress
    - sunglasses
    - suspenders
    - sweater
    - sweatpants
    - sweatshirt
    - sweatsuit
    - swimming costume
    - swimming shorts
    - swimming trunks
    - swimsuit
    - swimwear
    - t-shirt
    - tee
    - tailcoat
    - tam
    - tank top
    - tankini
    - teddy
    - thong
    - threads
    - tiara
    - tie
    - tie clip
    - tights
    - toga
    - togs
    - top
    - top coat
    - top hat
    - tracksuit
    - train
    - trainers
    - trench coat
    - trousers
    - trunks
    - tube top
    - tunic
    - turban
    - turtleneck
    - turtleneck shirt
    - tutu
    - tux
    - tuxedo
    - tweed jacket
    - twill
    - twin set
    - umbrella
    - underclothes
    - undershirt
    - underwear
    - uniform
    - veil
    - velcro
    - vest
    - vest underwear
    - vestments
    - visor
    - waders
    - waistcoat
    - waterproof
    - wear
    - wedding gown
    - wellingtons
    - wetsuit
    - white tie
    - wig
    - windbreaker
    - woollens
    - wrap
    - yoke
    - zip
    - zipper
    - zoris

garment_sizes_stop_filter: # Based on elasticsearch/wordlists/garment_sizes.txt
  type: stop
  stopwords:
    - xxxs
    - xxx-sm
    - xxx-small
    - xxs
    - xx-sm
    - xx-small
    - xs
    - x-sm
    - x-small
    - s
    - sm
    - small
    - m
    - medium
    - md
    - l
    - lg
    - large
    - xl
    - x-lg
    - x-large
    - xxl
    - xx-lg
    - xx-large
    - xxxl
    - xxx-lg
    - xxx-large

colors_stop_filter: # Based on elasticsearch/wordlists/colors.csv
  type: stop
  stopwords: 
    - air force blue
    - air superiority blue
    - alabama crimson
    - alice blue
    - alizarin crimson
    - alloy orange
    - almond
    - amaranth
    - amber
    - american rose
    - amethyst
    - android green
    - antique brass
    - antique fuchsia
    - antique ruby
    - antique white
    - ao
    - apple green
    - apricot
    - aqua
    - aquamarine
    - army green
    - arsenic
    - arylide yellow
    - ash grey
    - asparagus
    - atomic tangerine
    - auburn
    - aureolin
    - aurometalsaurus
    - avocado
    - azure
    - baby blue
    - baby blue eyes
    - baby pink
    - ball blue
    - banana mania
    - banana yellow
    - barn red
    - battleship grey
    - bazaar
    - beau blue
    - beaver
    - beige
    - bisque
    - bistre
    - bittersweet
    - bittersweet shimmer
    - black
    - black bean
    - black leather jacket
    - black olive
    - blanched almond
    - bleu de france
    - blizzard blue
    - blond
    - blue
    - blue bell
    - blue gray
    - blue sapphire
    - blush
    - bole
    - bondi blue
    - bone
    - boston university red
    - bottle green
    - boysenberry
    - brandeis blue
    - brass
    - brick red
    - bright cerulean
    - bright green
    - bright lavender
    - bright maroon
    - bright pink
    - bright turquoise
    - bright ube
    - brilliant lavender
    - brilliant rose
    - brink pink
    - british racing green
    - bronze
    - brown
    - bubble gum
    - bubbles
    - buff
    - bulgarian rose
    - burgundy
    - burlywood
    - burnt orange
    - burnt sienna
    - burnt umber
    - byzantine
    - byzantium
    - cadet
    - cadet blue
    - cadet grey
    - cadmium green
    - cadmium orange
    - cadmium red
    - cadmium yellow
    - cal poly green
    - cambridge blue
    - camel
    - cameo pink
    - camouflage green
    - canary yellow
    - candy apple red
    - candy pink
    - capri
    - caput mortuum
    - cardinal
    - caribbean green
    - carmine
    - carmine pink
    - carmine red
    - carnation pink
    - carnelian
    - carolina blue
    - carrot orange
    - catalina blue
    - ceil
    - celadon
    - celadon blue
    - celadon green
    - celeste
    - celestial blue
    - cerise
    - cerise pink
    - cerulean
    - cerulean blue
    - cerulean frost
    - cg blue
    - cg red
    - chamoisee
    - champagne
    - charcoal
    - charm pink
    - chartreuse
    - cherry
    - cherry blossom pink
    - chestnut
    - china pink
    - china rose
    - chinese red
    - chocolate
    - chrome yellow
    - cinereous
    - cinnabar
    - cinnamon
    - citrine
    - classic rose
    - cobalt
    - cocoa brown
    - coffee
    - columbia blue
    - congo pink
    - cool black
    - cool grey
    - copper
    - copper penny
    - copper red
    - copper rose
    - coquelicot
    - coral
    - coral pink
    - coral red
    - cordovan
    - corn
    - cornell red
    - cornflower blue
    - cornsilk
    - cosmic latte
    - cotton candy
    - cream
    - crimson
    - crimson glory
    - cyan
    - daffodil
    - dandelion
    - dark blue
    - dark brown
    - dark byzantium
    - dark candy apple red
    - dark cerulean
    - dark chestnut
    - dark coral
    - dark cyan
    - dark electric blue
    - dark goldenrod
    - dark gray
    - dark green
    - dark imperial blue
    - dark jungle green
    - dark khaki
    - dark lava
    - dark lavender
    - dark magenta
    - dark midnight blue
    - dark olive green
    - dark orange
    - dark orchid
    - dark pastel blue
    - dark pastel green
    - dark pastel purple
    - dark pastel red
    - dark pink
    - dark powder blue
    - dark raspberry
    - dark red
    - dark salmon
    - dark scarlet
    - dark sea green
    - dark sienna
    - dark slate blue
    - dark slate gray
    - dark spring green
    - dark tan
    - dark tangerine
    - dark taupe
    - dark terra cotta
    - dark turquoise
    - dark violet
    - dark yellow
    - dartmouth green
    - debian red
    - deep carmine
    - deep carmine pink
    - deep carrot orange
    - deep cerise
    - deep champagne
    - deep chestnut
    - deep coffee
    - deep fuchsia
    - deep jungle green
    - deep lilac
    - deep magenta
    - deep peach
    - deep pink
    - deep ruby
    - deep saffron
    - deep sky blue
    - deep tuscan red
    - denim
    - desert
    - desert sand
    - dim gray
    - dodger blue
    - dogwood rose
    - dollar bill
    - drab
    - duke blue
    - earth yellow
    - ebony
    - ecru
    - eggplant
    - eggshell
    - egyptian blue
    - electric blue
    - electric crimson
    - electric cyan
    - electric green
    - electric indigo
    - electric lavender
    - electric lime
    - electric purple
    - electric ultramarine
    - electric violet
    - electric yellow
    - emerald
    - english lavender
    - eton blue
    - fallow
    - falu red
    - fandango
    - fashion fuchsia
    - fawn
    - feldgrau
    - fern green
    - ferrari red
    - field drab
    - fire engine red
    - firebrick
    - flame
    - flamingo pink
    - flavescent
    - flax
    - floral white
    - fluorescent orange
    - fluorescent pink
    - fluorescent yellow
    - folly
    - forest green
    - french beige
    - french blue
    - french lilac
    - french lime
    - french raspberry
    - french rose
    - fuchsia
    - fuchsia pink
    - fuchsia rose
    - fulvous
    - fuzzy wuzzy
    - gainsboro
    - gamboge
    - ghost white
    - ginger
    - glaucous
    - glitter
    - gold
    - golden brown
    - golden poppy
    - golden yellow
    - goldenrod
    - granny smith apple
    - gray
    - green
    - grullo
    - guppie green
    - han blue
    - han purple
    - hansa yellow
    - harlequin
    - harvard crimson
    - harvest gold
    - heart gold
    - heliotrope
    - hollywood cerise
    - honeydew
    - honolulu blue
    - hot magenta
    - hot pink
    - hunter green
    - iceberg
    - icterine
    - imperial blue
    - inchworm
    - india green
    - indian red
    - indian yellow
    - indigo
    - international klein blue
    - international orange
    - iris
    - isabelline
    - islamic green
    - ivory
    - jade
    - jasmine
    - jasper
    - jazzberry jam
    - jet
    - jonquil
    - june bud
    - jungle green
    - kelly green
    - kenyan copper
    - khaki
    - ku crimson
    - la salle green
    - languid lavender
    - lapis lazuli
    - laser lemon
    - laurel green
    - lava
    - lavender blue
    - lavender blush
    - lavender
    - lavender gray
    - lavender indigo
    - lavender magenta
    - lavender mist
    - lavender pink
    - lavender purple
    - lavender rose
    - lawn green
    - lemon
    - lemon chiffon
    - lemon lime
    - licorice
    - light apricot
    - light blue
    - light brown
    - light carmine pink
    - light coral
    - light cornflower blue
    - light crimson
    - light cyan
    - light fuchsia pink
    - light goldenrod yellow
    - light gray
    - light green
    - light khaki
    - light pastel purple
    - light pink
    - light red ochre
    - light salmon
    - light salmon pink
    - light sea green
    - light sky blue
    - light slate gray
    - light taupe
    - light thulian pink
    - light yellow
    - lilac
    - lime
    - lime green
    - limerick
    - lincoln green
    - linen
    - lion
    - little boy blue
    - liver
    - lust
    - magenta
    - magic mint
    - magnolia
    - mahogany
    - maize
    - majorelle blue
    - malachite
    - manatee
    - mango tango
    - mantis
    - mardi gras
    - maroon
    - mauve
    - mauve taupe
    - mauvelous
    - maya blue
    - meat brown
    - medium aquamarine
    - medium blue
    - medium candy apple red
    - medium carmine
    - medium champagne
    - medium electric blue
    - medium jungle green
    - medium lavender magenta
    - medium orchid
    - medium persian blue
    - medium purple
    - medium ruby
    - medium sea green
    - medium slate blue
    - medium spring bud
    - medium spring green
    - medium taupe
    - medium turquoise
    - medium tuscan red
    - medium vermilion
    - mellow apricot
    - mellow yellow
    - melon
    - midnight blue
    - midnight green
    - mikado yellow
    - mint
    - mint cream
    - mint green
    - misty rose
    - moccasin
    - mode beige
    - moonstone blue
    - mordant red
    - moss green
    - mountain meadow
    - mountbatten pink
    - msu green
    - mulberry
    - mustard
    - myrtle
    - nadeshiko pink
    - napier green
    - naples yellow
    - navajo white
    - navy blue
    - neon carrot
    - neon fuchsia
    - neon green
    - new york pink
    - north texas green
    - ocean boat blue
    - ochre
    - office green
    - old gold
    - old lace
    - old lavender
    - old mauve
    - old rose
    - olive
    - olive drab
    - olivine
    - onyx
    - opera mauve
    - orange
    - orange peel
    - orchid
    - otter brown
    - ou crimson red
    - outer space
    - outrageous orange
    - oxford blue
    - pakistan green
    - palatinate blue
    - palatinate purple
    - pale aqua
    - pale blue
    - pale brown
    - pale carmine
    - pale cerulean
    - pale chestnut
    - pale copper
    - pale cornflower blue
    - pale gold
    - pale goldenrod
    - pale green
    - pale lavender
    - pale magenta
    - pale pink
    - pale plum
    - pale robin egg blue
    - pale silver
    - pale spring bud
    - pale taupe
    - pansy purple
    - papaya whip
    - paris green
    - pastel blue
    - pastel brown
    - pastel gray
    - pastel green
    - pastel magenta
    - pastel orange
    - pastel pink
    - pastel purple
    - pastel red
    - pastel violet
    - pastel yellow
    - patriarch
    - peach
    - peach puff
    - pear
    - pearl
    - pearl aqua
    - pearly purple
    - peridot
    - periwinkle
    - persian blue
    - persian green
    - persian indigo
    - persian orange
    - persian pink
    - persian plum
    - persian red
    - persian rose
    - persimmon
    - peru
    - phlox
    - phthalo blue
    - phthalo green
    - piggy pink
    - pine green
    - pink
    - pink lace
    - pink pearl
    - pink sherbet
    - pistachio
    - platinum
    - plum
    - portland orange
    - powder blue
    - princeton orange
    - prune
    - prussian blue
    - psychedelic purple
    - puce
    - pumpkin
    - purple heart
    - purple
    - purple mountain majesty
    - purple pizzazz
    - purple taupe
    - quartz
    - rackley
    - radical red
    - rajah
    - raspberry
    - raspberry glace
    - raspberry pink
    - raspberry rose
    - raw umber
    - razzle dazzle rose
    - razzmatazz
    - red
    - red devil
    - redwood
    - regalia
    - resolution blue
    - rich black
    - rich brilliant lavender
    - rich carmine
    - rich electric blue
    - rich lavender
    - rich lilac
    - rich maroon
    - rifle green
    - robin egg blue
    - rose
    - rose bonbon
    - rose ebony
    - rose gold
    - rose madder
    - rose pink
    - rose quartz
    - rose taupe
    - rose vale
    - rosewood
    - rosso corsa
    - rosy brown
    - royal azure
    - royal blue
    - royal fuchsia
    - royal purple
    - royal yellow
    - rubine red
    - ruby
    - ruby red
    - ruddy
    - ruddy brown
    - ruddy pink
    - rufous
    - russet
    - rust
    - rusty red
    - sacramento state green
    - saddle brown
    - safety orange
    - saffron
    - salmon
    - salmon pink
    - sand
    - sand dune
    - sandstorm
    - sandy brown
    - sandy taupe
    - sangria
    - sap green
    - sapphire
    - sapphire blue
    - satin sheen gold
    - scarlet
    - school bus yellow
    - sea blue
    - sea green
    - seal brown
    - seashell
    - selective yellow
    - sepia
    - shadow
    - shamrock green
    - shocking pink
    - sienna
    - silver
    - sinopia
    - skobeloff
    - sky blue
    - sky magenta
    - slate blue
    - slate gray
    - smalt
    - smokey topaz
    - smoky black
    - snow
    - spiro disco ball
    - spring bud
    - spring green
    - steel blue
    - stil de grain yellow
    - stizza
    - stormcloud
    - straw
    - sunglow
    - sunset
    - tan
    - tangelo
    - tangerine
    - tangerine yellow
    - tango pink
    - taupe
    - taupe gray
    - tea green
    - tea rose
    - teal
    - teal blue
    - teal green
    - telemagenta
    - terra cotta
    - thistle
    - thulian pink
    - tickle me pink
    - tiffany blue
    - timberwolf
    - titanium yellow
    - tomato
    - toolbox
    - topaz
    - tractor red
    - trolley grey
    - tropical rain forest
    - true blue
    - tufts blue
    - tumbleweed
    - turkish rose
    - turquoise
    - turquoise blue
    - turquoise green
    - tuscan red
    - twilight lavender
    - tyrian purple
    - ua blue
    - ua red
    - ube
    - ucla blue
    - ucla gold
    - ufo green
    - ultra pink
    - ultramarine
    - ultramarine blue
    - umber
    - unbleached silk
    - united nations blue
    - university of california gold
    - unmellow yellow
    - up forest green
    - up maroon
    - upsdell red
    - urobilin
    - usafa blue
    - usc cardinal
    - usc gold
    - utah crimson
    - vanilla
    - vegas gold
    - venetian red
    - verdigris
    - vermilion
    - veronica
    - violet
    - viridian
    - vivid auburn
    - vivid burgundy
    - vivid cerise
    - vivid tangerine
    - vivid violet
    - warm black
    - waterspout
    - wenge
    - wheat
    - white
    - white smoke
    - wild blue yonder
    - wild strawberry
    - wild watermelon
    - wine
    - wine dregs
    - wisteria
    - wood brown
    - xanadu
    - yale blue
    - yellow
    - yellow orange
    - zaffre
    - zinnwaldite brown

