---
article:
  dynamic:               strict
  properties:
    merchant_id:
      type:              keyword
    sku:
      type:              keyword
    name:
      type:              text
      analyzer:          article_name
      fields:
        raw:
          type:          keyword
          ignore_above:  500
    price:
      type:              scaled_float
      scaling_factor:    100
    description:
      type:              text
    link:
      type:              text
      analyzer:          simple
    created_at:
      type:              date
    updated_at:
      type:              date

