mappings:
  _default_:
    dynamic:                 strict
  article:
    properties:
      merchant_id:
        type:                keyword
      sku:
        type:                keyword
      name:
        type:                text
        analyzer:            article_name_analyzer
        fields:
          raw:
            type:            keyword
            ignore_above:    500
      price:
        type:                scaled_float
        scaling_factor:      100
      description:
        type:                text
        analyzer:            article_description_analyzer
      link:
        type:                text
        analyzer:            article_link_analyzer
      created_at:
        type:                date
      updated_at:
        type:                date

  price_history:
    properties:
      article_id:
        type:                keyword
      currency:
        type:                keyword
      history:
        type:                nested
        properties:
          price:
            type:            scaled_float
            scaling_factor:  100
          timestamp:
            type:            date
      created_at:
        type:                date
      updated_at:
        type:                date
