analysis:
  filter:
    colors_stop_filter:
      type:                          stop
      ignore_case:                   true
      stopwords_path:                stopwords/colors.txt
    garment_sizes_stop_filter:
      type:                          stop
      ignore_case:                   true
      stopwords_path:                stopwords/garment_sizes.txt
    garment_types_stop_filter:
      type:                          stop
      ignore_case:                   true
      stopwords_path:                stopwords/garment_types.txt
    url_stop_filter:
      type:                          stop
      ignore_case:                   true
      stopwords:
        - http
        - https
        - www
        - ftp

  char_filter:
    article_char_filter:
      type:                          mapping
      mappings_path:                 char_filter_mappings/article_mappings.txt

  analyzer:
    # This is a loose analyzer
    article_name_analyzer:
      type: custom
      char_filter:
        - article_char_filter
      tokenizer:                     standard
      filter:
        - standard
        - lowercase
        - asciifolding                # Fold to ascii
        - apostrophe                  # Remove apostrophe
        - stop                        # Remove common english stop words
        - snowball                    # Simplify terms to base, remove plurials

    # This is a strict analyzer, which is
    # heavily filtered, field indexed with this
    # analyzer will be given a boost
    article_name_strict_keyword_analyzer:
      type:                          custom
      char_filter:
        - article_char_filter
      tokenizer:                     standard
      filter:
        - standard
        - lowercase
        - asciifolding                # Fold to ascii
        - apostrophe                  # Remove apostrophe
        - stop                        # Remove common english stop words
        - colors_stop_filter          # Remove colors
        - garment_types_stop_filter   # Remove types
        - garment_sizes_stop_filter   # Remove sizes
        - snowball                    # Simplify terms to base, remove plurials

    article_description_analyzer:
      type:                          custom
      char_filter:
        - article_char_filter
      tokenizer:                     standard
      filter:
        - standard
        - lowercase
        - asciifolding                # Fold to ascii
        - apostrophe                  # Remove apostrophe
        - stop                        # Remove common english stop words
        - colors_stop_filter          # Remove colors
        - garment_types_stop_filter   # Remove types
        - garment_sizes_stop_filter   # Remove sizes
        - snowball                    # Simplify terms to base, remove plurials

    article_link_analyzer:
      type:                          custom
      tokenizer:                     standard
      filter:
        - standard
        - lowercase
        - asciifolding
        - url_stop_filter


