# RethinkDB

default: &default
  host: localhost
  port: 28015
#  db: buyma_insider_development
#  user:
#  password:
#  timeout:

development:
  <<: *default
  db: buyma_insider_development

test:
  <<: *default
  db: buyma_insider_test

staging:
  <<: *default
  db: buyma_insider_staging

production:
  <<: *default
  db: buyma_insider_production
