# rethinkdb

default: &default
  uri: rethinkdb://localhost:28015/buyma_insider_development

development:
  <<: *default

test:
  <<: *default
  uri: rethinkdb://localhost:28015/buyma_insider_test

staging:
  <<: *default
  uri: rethinkdb://localhost:28015/buyma_insider_staging

production:
  <<: *default
  uri: rethinkdb://localhost:28015/buyma_insider_production
