default:              &default
  root:               &default_process
    severity:         debug
    additive:         false
    level:            &default_level
      debug:          &default_severity
        pattern:      "[%d] %-5l -- %c : %m\n"
        location:     ./log/root.debug.log
        age:          daily
      info:
        <<:           *default_severity
        location:     ./log/root.log
      warn:
        <<:           *default_severity
      error:
        <<:           *default_severity
      fatal:
        <<:           *default_severity
  sinatra:
    <<:               *default_process
  database:
    <<:               *default_process
  sidekiq:
    <<:               *default_process
  elasticsearch:
    <<:               *default_process
  httplog:
    <<:               *default_process

development:
  <<:                 *default

test:
  <<:                 *default

staging:
  <<:                 *default

production:
  <<:                 *default
  root:
    <<:               *default_process
    severity:         info
  database:
    <<:               *default_process
    severity:         info
  sinatra:
    <<:               *default_process
    severity:         info
  sidekiq:
    <<:               *default_process
    severity:         info
  elasticsearch:
    <<:               *default_process
    severity:         info
  httplog:
    <<:               *default_process
    severity:         info
