After adding merchants or indexes,
1. Need to update elastic search if there are new merchants, because
   it will create new index for this merchant
2. Run app:update_merchants rake tasks to update all indices and merchants


# 2016 - 2017
ssense:
  code:           sse
  name:           ssense
  domain:         //www.ssense.com
  pager_css:      div.browsing-pagination ul.nav
  item_css:       div.browsing-product-list figure.browsing-product-item
  index_pages:
    - /en-ca/men
    - /en-ca/women
  ssl:            true

getoutside:
  code:           get
  name:           getoutside
  domain:         //www.getoutsideshoes.com
  ssl:            true
  pager_css:      div.pager > div.pages ol
  item_css:       ul.products-grid li.item
  index_pages:
    - /new-arrivals.html
    - /mens.html
    - /womens.html
    - /kid-s.html
    - /accessories.html
    - /sale.html

zara:
  code:           zar
  name:           zara
  domain:         //www.zara.com/ca/en
  ssl:            true
  pager_css:      ~
  item_css:       ul.product-list li.product
  index_pages:
    - /woman/new-in-c840002.html
    - /woman/new-in-c805003.html
    - /woman/best-sellers-c858027.html
    - /woman/outerwear/view-all-c733882.html
    - /woman/trench-coats-c749003.html
    - /woman/jackets-c269184.html
    - /woman/blazers-c756615.html
    - /woman/knitwear/view-all-c733910.html
    - /woman/dresses/view-all-c733885.html
    - /woman/jumpsuits-c663016.html
    - /woman/tops/view-all-c733890.html
    - /woman/t-shirts/view-all-c733912.html
    - /woman/trousers/view-all-c733898.html
    - /woman/jeans/view-all-c733918.html
    - /woman/skirts/view-all-c733908.html
    - /woman/shorts-c733903.html
    - /woman/sweatshirts-c733914.html
    - /woman/shoes/view-all-c734142.html
    - /woman/bags/view-all-c734144.html
    - /woman/accessories/view-all-c733915.html
    - /woman/swimwear-c764512.html
    - /woman/special-prices-c763514.html
    - /woman/suiting-time-c507505.html
    - /woman/faux-fur-luxe-c835053.html
    - /trf/new-in-c840006.html
    - /trf/outerwear-c665507.html
    - /trf/dresses/view-all-c965503.html
    - /trf/tops-c269211.html
    - /trf/t-shirts/view-all-c965048.html
    - /trf/knitwear-c695503.html
    - /trf/trousers-c269212.html
    - /trf/shorts-c734192.html
    - /trf/jeans-c271018.html
    - /trf/skirts-c269213.html
    - /trf/sweatshirts-c669532.html
    - /trf/shoes-c269216.html
    - /trf/bags-c269223.html
    - /trf/denim/view-all-c966004.html
    - /man/new-in-c744526.html
    - /man/best-sellers-c858034.html
    - /man/basics/view-all-c501501.html
    - /man/outerwear-c277002.html
    - /man/jackets/view-all-c758501.html
    - /man/blazers-c269232.html
    - /man/suits-c269233.html
    - /man/trousers/view-all-c733862.html
    - /man/shorts-c637013.html
    - /man/jeans-c269235.html
    - /man/shirts/view-all-c733865.html
    - /man/t-shirts/view-all-c733866.html
    - /man/polos-c493002.html
    - /man/sweatshirts-c309502.html
    - /man/sweaters-c269238.html
    - /man/shoes/view-all-c734091.html
    - /man/bags/view-all-c734090.html
    - /man/accessories/view-all-c733868.html
    - /man/socks-c637031.html
    - /man/underwear-c893583.html
    - /man/swimwear-c637012.html
    - /man/special-prices-c661502.html
    - /man/denim-essentials-c671070.html
    - /man/dark-collection-c856018.html

# july 2017
octobersveryown:
  code:           ovo
  name:           octobersveryown
  domain:         //ca.octobersveryown.com
  ssl:            true
  pager_css:      ~
  item_css:       main.main-content div.grid__item
  index_pages:
    - /collections/all

# july 2017
livestock:
  code:           ltk
  name:           livestock
  domain:         //www.deadstock.ca
  ssl:            true
  pager_css:      div.paginate
  item_css:       div.container.main.content div.products div.four.columns.thumbnail
  index_pages:
    - /collections/new-arrivals
    - /collections/footwear

# august 27, 2017
canada_goose:
  code:           goo
  name:           canada_goose
  domain:         //www.canadagoose.com
  ssl:            true
  pager_css:      ~
  item_css:       div#primary ul#search-result-items li div.product-tile
  index_pages:
    - /ca/en/shop/men
    - /ca/en/shop/women
    - /ca/en/shop/kids

arcteryx:
  code:           arc
  name:           arcteryx
  domain:         //arcteryx.com
  ssl:            true
  pager_css:      ~
  item_css:       div#divContent div.searchResult
  index_pages:
    - /ProductFind.aspx?country=ca&language=en&gender=Mens
    - /ProductFind.aspx?country=ca&language=en&gender=Womens




