ssense:
  code:             sse
  name:             ssense
  domain:           //www.ssense.com
  pager_css:        div.browsing-pagination ul.nav
  item_css:         div.browsing-product-list figure.browsing-product-item
  index_pages:
    - /en-ca/men
    - /en-ca/women
  ssl:              true

getoutside:
  code:             get
  name:             getoutside
  domain:           //www.getoutsideshoes.com
  ssl:              true
  pager_css:        div.pager > div.pages ol
  item_css:         ul.products-grid li.item
  index_pages:
    - /new-arrivals.html
    - /mens.html
    - /womens.html
    - /kid-s.html
    - /accessories.html
    - /sale.html

zara:
  code:             zar
  name:             zara
  domain:           //www.zara.com/ca/en
  ssl:              true
  pager_css:
  item_css:         ul.product-list li.product
  index_pages:
    - /woman/new-in-c840002.html
    - /woman/new-in-c805003.html

octobersveryown:
  code:             ovo
  name:             octobersveryown
  domain:           //ca.octobersveryown.com
  ssl:              true
  pager_css:
  item_css:         main.main-content div.grid__item
  index_pages:
    - /collections/all

#livestock:
#  code:             ltk
#  name:             livestock
#  domain:           //www.deadstock.ca
#  ssl:              true
#  pager_css:        div.container.main.content > div.products div.paginate
#  item_css:         div.container.main.content > div.products > div.columns
#  index_pages:
#    - /collections/new-arrivals
