ssense:
  id:               sse
  name:             ssense
  domain:           //www.ssense.com
  pager_css:        div.browsing-pagination ul.nav
  item_css:         div.browsing-product-list div.browsing-product-item
  index_pages:
    - /en-ca/men
    - /en-ca/women
  ssl:              true

# @deprecated shoeme is out of business
#shoeme:
#  id:               sho
#  name:             shoeme
#  domain:           //shoeme.ecomm-nav.com
#  pager_css:        div.nxt-pagination
#  item_css:         ul.product-list li.product-li
#  index_pages:
#    - collections/womens-shoes
#    - collections/mens-shoes
#    - collections/kids
#    - collections/all-bags
#    - collections/sale
#  ssl:              false

getoutside:
  id:               get
  name:             getoutside
  domain:           //www.getoutsideshoes.com
  pager_css:        div.browing-pagination ui.nav
  item_css:         ul.products-grid li.item
  index_pages:
    - /new-arrivals.html
    - /mens.html
    - /womens.html
    - /kid-s.html
    - /accessories.html
    - /sale.html
  ssl:              false

zara:
  id:               zar
  name:             zara
  domain:           //www.zara.com/ca/en
  pager_css:
  item_css:         ul.product-list li.product
  index_pages:
    - /woman/new-in-c805003.html
  ssl:              true

octobersveryown:
  id:               ovo
  name:             octobersveryown
  domain:           //ca.octobersveryown.com
  pager_css:
  item_css:         main.main-content div.grid__item
  index_pages:
    - /collections/all
  ssl:              true

#livestock:
#  id:               ltk
#  name:             livestock
#  domain:           //www.deadstock.ca
#  pager_css:        div.container.main.content > div.products div.paginate
#  item_css:         div.container.main.content > div.products > div.columns
#  index_pages:
#    - /collections/new-arrivals
#  ssl:              true
