ssense:
  id:           sse
  name:         ssense
  base_url:     //www.ssense.com
  pager_css:    div.browsing-pagination ul.nav
  item_css:     div.browsing-product-list div.browsing-product-item
  index_pages:
    - en-ca/men
    - en-ca/women
  ssl: true

shoeme:
  id:           sho
  name:         shoeme
  base_url:     //shoeme.ecomm-nav.com
  pager_css:    div.nxt-pagination
  item_css:     ul.product-list li.product-li
  index_pages:
    - collections/womens-shoes
    - collections/mens-shoes
    - collections/kids
    - collections/all-bags
    - collections/sale
  ssl: false

getoutside:
  id:           get
  name:         getoutside
  base_url:     //www.getoutsideshoes.com
  pager_css:    div.pager
  item_css:     ul.products-grid li.item
  index_pages:
    - new-arrivals.html
    - mens.html
    - womens.html
    - kid-s.html
    - accessories.html
    - sale.html
  ssl: false

zara:
  id:           zar
  name:         zara
  base_url:     //www.zara.com/ca/en
  pager_css:
  item_css:     ul.product-list li.product
  index_pages:
    - women/new-in-c805003.html
  ssl: false
