# postgres database configuration

default: &default
  adapter:  postgresql
  host:     localhost
  username: postgres
  password: mobara
  pool:     5

development:
  <<: *default
  database: buyma_insider_development

test:
  <<: *default
  database: buyma_insider_test

staging:
  <<: *default
  database: buyma_insider_staging

production:
  <<: *default
  database: buyma_insider_production
  pool: 10 # 2 unicorn workers + 5 sidekiq job threads
