# Redis
default: &default
  host: 127.0.0.1
  port: 6379
  db: 1
#  password:
#  path:
#  connect_timeout:  0.2,
#  read_timeout: 1.0,
#  write_timeout: 0.5

development:
  <<: *default

unittest:
  <<: *default

integrationtest:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
