# Redis
default:          &default
  global:         &default_process
    host:         127.0.0.1
    port:         6379
    db:           0
    pool_size:    5
  sinatra:
    <<:           *default_process
    db:           0
    # marshalling:  false, use raw instead
  serializer:
    <<:           *default_process
    db:           1
  message_bus:
    <<:           *default_process
    db:           2
  sidekiq:
    <<:           *default_process
    db:           3
    marshalling:  false
    # concurrency + 5 see https://github.com/mperham/sidekiq/issues/117#issuecomment-168971492
    pool_size:    10


#  password:
#  path:
#  connect_timeout: 0.2,
#  read_timeout:  1.0,
#  write_timeout: 0.5

development:
  <<:             *default

test:
  <<:             *default

staging:
  <<:             *default

# Change this to sock on production
production:
  <<:             *default
