# Configuration for sidekiq cron jobs
merchant_crawl_schedule_worker:
  cron:                         '0 20 * * *'
  class:                        'MerchantCrawlScheduleWorker'
#  queue:                       default
#  args:                        []

open_exchange_rates_worker:
  cron:                         '0 * * * *'
  class:                        'OpenExchangeRatesWorker'

rethinkdb_backup_worker:
  cron:                         '0 1 * * *'
  class:                        'RethinkdbBackupWorker'


