pidfile:       /usr/local/var/run/sidekiq.pid
logfile:       /usr/local/var/log/sidekiq.log
concurrency:   5
queues:
  - [critical, 4]
  - [crawl, 2]
  - default
staging:
  concurrency: 5
production:
  concurrency: 5

