_source: false
query:
  bool:
    must:
      match:
        name: '{{article_name_query}}'
        name.strict_keyword: '{{article_name_query}}'
    must_not:
      ids:
        values: '{{#toJson}}excluded_article_ids{{/toJson}}'
# sort: order by most relevant
from: '{{from}}{{^from}}0{{/from}}'
size: '{{size}}{{^size}}20{{/size}}'