_source: false
query:
  bool:
    must:
      multi_match:
        query: '{{article_name_query}}'
        fields:
          - name
          - name.strict_keyword^3
        type: most_fields
    must_not:
      ids:
        values: '{{#toJson}}excluded_article_ids{{/toJson}}'
# sort: order by most relevant
from: '{{from}}{{^from}}0{{/from}}'
size: '{{size}}{{^size}}20{{/size}}'
