_source: false
query:
  bool:
    must:
      match:
        name: '{{article_name_query}}'
    should:
      - match:
          name.strict_keyword:
            query: '{{article_name_query}}'
            boost: 3 # 3 is arbitrary
    minimum_should_match: 0 # this is the default
#    filter:
#      range:
#        created_at:
#          gte: '{{created_at}}{{^created_at}}now-1w{{/created_at}}'
#    must_not:
#      range:
#        updated_at:
#          lt: now+2y
sort: '{{#toJson}}order_by{{/toJson}}'
from: '{{from}}{{^from}}0{{/from}}'
size: '{{size}}{{^size}}20{{/size}}'
#params:
#  article_name_query: leather crossbody
#  from: 0
#  size: 5
